//! Tests for index metadata generated by `#[derive(Model)]` from field-level
//! attributes and foreign keys.

use tork_orm::dialect::SqliteDialect;
use tork_orm::prelude::*;

#[derive(Debug, Clone, Model)]
#[table(name = "users")]
struct User {
    #[field(primary_key, auto)]
    id: i64,
    #[field(varchar(length = 50), unique)]
    username: String,
    #[field(index)]
    email: String,
    is_active: bool,
}

#[derive(Debug, Clone, Model)]
#[table(name = "posts")]
struct Post {
    #[field(primary_key, auto)]
    id: i64,
    #[field(foreign_key = User::id)]
    user_id: i64,
    title: String,
}

#[derive(Debug, Clone, Model)]
#[table(name = "tags")]
struct Tag {
    #[field(primary_key, auto)]
    id: i64,
    // An explicit unique index on the foreign key suppresses the automatic one.
    #[field(foreign_key = User::id, unique)]
    owner_id: i64,
}

#[derive(Debug, Clone, Model)]
#[table(name = "events")]
struct Event {
    #[field(primary_key, auto)]
    id: i64,
    // `index = false` opts out of the automatic foreign-key index.
    #[field(foreign_key = User::id, index = false)]
    user_id: i64,
}

#[test]
fn field_unique_and_index_become_indexes() {
    let indexes = User::indexes();
    assert_eq!(indexes.len(), 2);

    let username = indexes.iter().find(|i| i.name == "users_username_key").unwrap();
    assert!(username.unique);
    assert_eq!(username.columns.len(), 1);
    assert_eq!(username.columns[0].name, "username");

    let email = indexes.iter().find(|i| i.name == "users_email_idx").unwrap();
    assert!(!email.unique);
    assert_eq!(email.columns[0].name, "email");
}

#[test]
fn foreign_key_gets_automatic_index() {
    let indexes = Post::indexes();
    assert_eq!(indexes.len(), 1);
    assert_eq!(indexes[0].name, "posts_user_id_idx");
    assert!(!indexes[0].unique);
    assert_eq!(indexes[0].columns[0].name, "user_id");
}

#[test]
fn explicit_index_suppresses_foreign_key_auto_index() {
    let indexes = Tag::indexes();
    // Only the unique index, not an additional auto-index on the same column.
    assert_eq!(indexes.len(), 1);
    assert_eq!(indexes[0].name, "tags_owner_id_key");
    assert!(indexes[0].unique);
}

#[test]
fn index_false_opts_out_of_foreign_key_index() {
    assert!(Event::indexes().is_empty());
}

#[test]
fn index_statements_render() {
    let dialect = SqliteDialect::new();
    let statements = User::index_statements(&dialect).unwrap();
    assert!(statements.contains(
        &"CREATE UNIQUE INDEX \"users_username_key\" ON \"users\" (\"username\")".to_string()
    ));
    assert!(statements
        .contains(&"CREATE INDEX \"users_email_idx\" ON \"users\" (\"email\")".to_string()));
}
