-- revision: cb6cfb8684d9
-- down_revision: 
-- name: initial_schema

-- migrate:up
CREATE TABLE "users" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "email" VARCHAR(255) NOT NULL, "phone" VARCHAR(32), "password_hash" TEXT NOT NULL, "first_name" TEXT, "last_name" TEXT, "role" TEXT NOT NULL CHECK ("role" IN ('customer', 'admin')), "status" TEXT NOT NULL CHECK ("status" IN ('active', 'passive', 'banned')), "email_verified_at" TIMESTAMP, "last_login_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "deleted_at" TIMESTAMP);
CREATE UNIQUE INDEX "users_email_key" ON "users" ("email");
CREATE UNIQUE INDEX "users_phone_key" ON "users" ("phone");
CREATE TABLE "addresses" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "user_id" BIGINT NOT NULL, "address_type" TEXT NOT NULL CHECK ("address_type" IN ('shipping', 'billing')), "title" TEXT, "country_code" TEXT NOT NULL, "city" TEXT NOT NULL, "district" TEXT, "postal_code" TEXT, "line1" TEXT NOT NULL, "line2" TEXT, "recipient_name" TEXT NOT NULL, "recipient_phone" TEXT NOT NULL, "is_default" BOOLEAN NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE);
CREATE INDEX "addresses_user_id_idx" ON "addresses" ("user_id");
CREATE TABLE "vendors" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "name" TEXT NOT NULL, "slug" VARCHAR(180) NOT NULL, "status" TEXT NOT NULL CHECK ("status" IN ('pending', 'active', 'suspended')), "legal_name" TEXT, "tax_number" TEXT, "contact_email" TEXT, "contact_phone" TEXT, "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "deleted_at" TIMESTAMP);
CREATE UNIQUE INDEX "vendors_slug_key" ON "vendors" ("slug");
CREATE TABLE "vendor_members" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "vendor_id" BIGINT NOT NULL, "user_id" BIGINT NOT NULL, "role" TEXT NOT NULL CHECK ("role" IN ('owner', 'manager', 'staff')), "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY ("vendor_id") REFERENCES "vendors" ("id") ON DELETE CASCADE, FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE);
CREATE INDEX "vendor_members_user_id_idx" ON "vendor_members" ("user_id");
CREATE UNIQUE INDEX "uq_vendor_member" ON "vendor_members" ("vendor_id", "user_id");
CREATE TABLE "brands" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "name" TEXT NOT NULL, "slug" VARCHAR(180) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX "brands_slug_key" ON "brands" ("slug");
CREATE TABLE "categories" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "parent_id" BIGINT, "name" TEXT NOT NULL, "slug" VARCHAR(180) NOT NULL, "description" TEXT, "sort_order" INTEGER NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY ("parent_id") REFERENCES "categories" ("id") ON DELETE SET NULL);
CREATE INDEX "categories_parent_id_idx" ON "categories" ("parent_id");
CREATE UNIQUE INDEX "categories_slug_key" ON "categories" ("slug");
CREATE TABLE "products" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "vendor_id" BIGINT NOT NULL, "brand_id" BIGINT, "title" TEXT NOT NULL, "slug" TEXT NOT NULL, "short_description" TEXT, "description" TEXT, "status" TEXT NOT NULL CHECK ("status" IN ('draft', 'active', 'archived')), "seo_title" TEXT, "seo_description" TEXT, "extra_data" TEXT, "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "deleted_at" TIMESTAMP, FOREIGN KEY ("vendor_id") REFERENCES "vendors" ("id") ON DELETE CASCADE, FOREIGN KEY ("brand_id") REFERENCES "brands" ("id") ON DELETE SET NULL);
CREATE INDEX "products_brand_id_idx" ON "products" ("brand_id");
CREATE UNIQUE INDEX "uq_products_vendor_slug" ON "products" ("vendor_id", "slug");
CREATE TABLE "product_categories" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "product_id" BIGINT NOT NULL, "category_id" BIGINT NOT NULL, "is_primary" BOOLEAN NOT NULL, FOREIGN KEY ("product_id") REFERENCES "products" ("id") ON DELETE CASCADE, FOREIGN KEY ("category_id") REFERENCES "categories" ("id") ON DELETE CASCADE);
CREATE INDEX "product_categories_category_id_idx" ON "product_categories" ("category_id");
CREATE UNIQUE INDEX "uq_product_category" ON "product_categories" ("product_id", "category_id");
CREATE TABLE "product_variants" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "product_id" BIGINT NOT NULL, "sku" VARCHAR(100) NOT NULL, "barcode" VARCHAR(100), "title" TEXT, "price_cents" BIGINT NOT NULL, "compare_at_price_cents" BIGINT, "cost_price_cents" BIGINT, "currency" VARCHAR(3) NOT NULL, "weight_grams" INTEGER, "dimensions" TEXT, "attributes" TEXT, "is_active" BOOLEAN NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "deleted_at" TIMESTAMP, FOREIGN KEY ("product_id") REFERENCES "products" ("id") ON DELETE CASCADE, CHECK (price_cents >= 0));
CREATE INDEX "product_variants_product_id_idx" ON "product_variants" ("product_id");
CREATE UNIQUE INDEX "product_variants_sku_key" ON "product_variants" ("sku");
CREATE UNIQUE INDEX "product_variants_barcode_key" ON "product_variants" ("barcode");
CREATE TABLE "product_images" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "product_id" BIGINT NOT NULL, "variant_id" BIGINT, "url" TEXT NOT NULL, "alt_text" TEXT, "sort_order" INTEGER NOT NULL, "is_primary" BOOLEAN NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY ("product_id") REFERENCES "products" ("id") ON DELETE CASCADE, FOREIGN KEY ("variant_id") REFERENCES "product_variants" ("id") ON DELETE SET NULL);
CREATE INDEX "product_images_product_id_idx" ON "product_images" ("product_id");
CREATE INDEX "product_images_variant_id_idx" ON "product_images" ("variant_id");
CREATE TABLE "inventory_locations" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "vendor_id" BIGINT NOT NULL, "name" TEXT NOT NULL, "country_code" TEXT NOT NULL, "city" TEXT NOT NULL, "address_line" TEXT, "is_active" BOOLEAN NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY ("vendor_id") REFERENCES "vendors" ("id") ON DELETE CASCADE);
CREATE INDEX "inventory_locations_vendor_id_idx" ON "inventory_locations" ("vendor_id");
CREATE TABLE "inventory_items" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "variant_id" BIGINT NOT NULL, "location_id" BIGINT NOT NULL, "quantity_on_hand" INTEGER NOT NULL, "quantity_reserved" INTEGER NOT NULL, "reorder_level" INTEGER NOT NULL, "version" BIGINT NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY ("variant_id") REFERENCES "product_variants" ("id") ON DELETE CASCADE, FOREIGN KEY ("location_id") REFERENCES "inventory_locations" ("id") ON DELETE CASCADE, CHECK (quantity_on_hand >= 0), CHECK (quantity_reserved >= 0));
CREATE INDEX "inventory_items_location_id_idx" ON "inventory_items" ("location_id");
CREATE UNIQUE INDEX "uq_inventory_variant_location" ON "inventory_items" ("variant_id", "location_id");
CREATE TABLE "inventory_movements" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "inventory_item_id" BIGINT NOT NULL, "movement_type" TEXT NOT NULL CHECK ("movement_type" IN ('purchase', 'sale', 'return', 'adjustment', 'reservation', 'release')), "quantity" INTEGER NOT NULL, "reason" TEXT, "reference_type" TEXT, "reference_id" BIGINT, "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY ("inventory_item_id") REFERENCES "inventory_items" ("id") ON DELETE CASCADE, CHECK (quantity <> 0));
CREATE INDEX "inventory_movements_inventory_item_id_idx" ON "inventory_movements" ("inventory_item_id");
CREATE TABLE "carts" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "user_id" BIGINT, "session_id" TEXT, "currency" VARCHAR(3) NOT NULL, "is_active" BOOLEAN NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE);
CREATE INDEX "carts_user_id_idx" ON "carts" ("user_id");
CREATE TABLE "cart_items" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "cart_id" BIGINT NOT NULL, "variant_id" BIGINT NOT NULL, "quantity" INTEGER NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY ("cart_id") REFERENCES "carts" ("id") ON DELETE CASCADE, FOREIGN KEY ("variant_id") REFERENCES "product_variants" ("id") ON DELETE RESTRICT, CHECK (quantity > 0));
CREATE INDEX "cart_items_variant_id_idx" ON "cart_items" ("variant_id");
CREATE UNIQUE INDEX "uq_cart_variant" ON "cart_items" ("cart_id", "variant_id");
CREATE TABLE "coupons" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "vendor_id" BIGINT, "code" VARCHAR(64) NOT NULL, "status" TEXT NOT NULL CHECK ("status" IN ('active', 'passive', 'expired')), "discount_type" TEXT NOT NULL CHECK ("discount_type" IN ('percentage', 'fixed_amount')), "discount_value" BIGINT NOT NULL, "max_discount_amount_cents" BIGINT, "min_order_amount_cents" BIGINT, "usage_limit" INTEGER, "usage_count" INTEGER NOT NULL, "per_user_limit" INTEGER, "starts_at" TIMESTAMP, "ends_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY ("vendor_id") REFERENCES "vendors" ("id") ON DELETE CASCADE, CHECK (discount_value >= 0));
CREATE INDEX "coupons_vendor_id_idx" ON "coupons" ("vendor_id");
CREATE UNIQUE INDEX "coupons_code_key" ON "coupons" ("code");
CREATE TABLE "orders" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "user_id" BIGINT, "coupon_id" BIGINT, "order_number" VARCHAR(64) NOT NULL, "status" TEXT NOT NULL CHECK ("status" IN ('pending', 'confirmed', 'processing', 'shipped', 'delivered', 'cancelled', 'refunded')), "currency" VARCHAR(3) NOT NULL, "subtotal_cents" BIGINT NOT NULL, "discount_total_cents" BIGINT NOT NULL, "tax_total_cents" BIGINT NOT NULL, "shipping_total_cents" BIGINT NOT NULL, "grand_total_cents" BIGINT NOT NULL, "customer_email" TEXT NOT NULL, "customer_phone" TEXT, "placed_at" TIMESTAMP, "cancelled_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE SET NULL, FOREIGN KEY ("coupon_id") REFERENCES "coupons" ("id") ON DELETE SET NULL, CHECK (subtotal_cents >= 0), CHECK (grand_total_cents >= 0));
CREATE INDEX "orders_user_id_idx" ON "orders" ("user_id");
CREATE INDEX "orders_coupon_id_idx" ON "orders" ("coupon_id");
CREATE UNIQUE INDEX "orders_order_number_key" ON "orders" ("order_number");
CREATE TABLE "order_items" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "order_id" BIGINT NOT NULL, "vendor_id" BIGINT NOT NULL, "product_id" BIGINT NOT NULL, "variant_id" BIGINT NOT NULL, "sku" TEXT NOT NULL, "product_title" TEXT NOT NULL, "variant_title" TEXT, "quantity" INTEGER NOT NULL, "unit_price_cents" BIGINT NOT NULL, "discount_total_cents" BIGINT NOT NULL, "tax_total_cents" BIGINT NOT NULL, "line_total_cents" BIGINT NOT NULL, "attributes_snapshot" TEXT, "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY ("order_id") REFERENCES "orders" ("id") ON DELETE CASCADE, FOREIGN KEY ("vendor_id") REFERENCES "vendors" ("id") ON DELETE RESTRICT, FOREIGN KEY ("product_id") REFERENCES "products" ("id") ON DELETE RESTRICT, FOREIGN KEY ("variant_id") REFERENCES "product_variants" ("id") ON DELETE RESTRICT, CHECK (quantity > 0), CHECK (unit_price_cents >= 0));
CREATE INDEX "order_items_order_id_idx" ON "order_items" ("order_id");
CREATE INDEX "order_items_vendor_id_idx" ON "order_items" ("vendor_id");
CREATE INDEX "order_items_product_id_idx" ON "order_items" ("product_id");
CREATE INDEX "order_items_variant_id_idx" ON "order_items" ("variant_id");
CREATE TABLE "order_addresses" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "order_id" BIGINT NOT NULL, "address_type" TEXT NOT NULL CHECK ("address_type" IN ('shipping', 'billing')), "recipient_name" TEXT NOT NULL, "recipient_phone" TEXT NOT NULL, "country_code" TEXT NOT NULL, "city" TEXT NOT NULL, "district" TEXT, "postal_code" TEXT, "line1" TEXT NOT NULL, "line2" TEXT, "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY ("order_id") REFERENCES "orders" ("id") ON DELETE CASCADE);
CREATE UNIQUE INDEX "uq_order_address_type" ON "order_addresses" ("order_id", "address_type");
CREATE TABLE "coupon_redemptions" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "coupon_id" BIGINT NOT NULL, "order_id" BIGINT NOT NULL, "user_id" BIGINT, "discount_amount_cents" BIGINT NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY ("coupon_id") REFERENCES "coupons" ("id") ON DELETE CASCADE, FOREIGN KEY ("order_id") REFERENCES "orders" ("id") ON DELETE CASCADE, FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE SET NULL);
CREATE INDEX "coupon_redemptions_order_id_idx" ON "coupon_redemptions" ("order_id");
CREATE INDEX "coupon_redemptions_user_id_idx" ON "coupon_redemptions" ("user_id");
CREATE UNIQUE INDEX "uq_coupon_order_redemption" ON "coupon_redemptions" ("coupon_id", "order_id");
CREATE TABLE "payments" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "order_id" BIGINT NOT NULL, "provider" TEXT NOT NULL CHECK ("provider" IN ('stripe', 'iyzico', 'paypal', 'manual')), "method" TEXT NOT NULL CHECK ("method" IN ('card', 'bank_transfer', 'cash_on_delivery')), "status" TEXT NOT NULL CHECK ("status" IN ('pending', 'authorized', 'paid', 'failed', 'cancelled', 'refunded')), "amount_cents" BIGINT NOT NULL, "currency" VARCHAR(3) NOT NULL, "transaction_id" TEXT, "provider_reference" TEXT, "raw_response" TEXT, "paid_at" TIMESTAMP, "failed_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY ("order_id") REFERENCES "orders" ("id") ON DELETE CASCADE, CHECK (amount_cents >= 0));
CREATE INDEX "payments_order_id_idx" ON "payments" ("order_id");
CREATE TABLE "shipments" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "order_id" BIGINT NOT NULL, "vendor_id" BIGINT NOT NULL, "status" TEXT NOT NULL CHECK ("status" IN ('pending', 'preparing', 'shipped', 'delivered', 'failed', 'returned')), "carrier" TEXT, "tracking_number" TEXT, "tracking_url" TEXT, "shipped_at" TIMESTAMP, "delivered_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY ("order_id") REFERENCES "orders" ("id") ON DELETE CASCADE, FOREIGN KEY ("vendor_id") REFERENCES "vendors" ("id") ON DELETE RESTRICT);
CREATE INDEX "shipments_order_id_idx" ON "shipments" ("order_id");
CREATE INDEX "shipments_vendor_id_idx" ON "shipments" ("vendor_id");
CREATE TABLE "shipment_items" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "shipment_id" BIGINT NOT NULL, "order_item_id" BIGINT NOT NULL, "quantity" INTEGER NOT NULL, FOREIGN KEY ("shipment_id") REFERENCES "shipments" ("id") ON DELETE CASCADE, FOREIGN KEY ("order_item_id") REFERENCES "order_items" ("id") ON DELETE CASCADE, CHECK (quantity > 0));
CREATE INDEX "shipment_items_order_item_id_idx" ON "shipment_items" ("order_item_id");
CREATE UNIQUE INDEX "uq_shipment_order_item" ON "shipment_items" ("shipment_id", "order_item_id");
CREATE TABLE "return_requests" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "order_id" BIGINT NOT NULL, "user_id" BIGINT, "status" TEXT NOT NULL CHECK ("status" IN ('requested', 'approved', 'rejected', 'received', 'refunded')), "reason" TEXT, "requested_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "resolved_at" TIMESTAMP, "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY ("order_id") REFERENCES "orders" ("id") ON DELETE CASCADE, FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE SET NULL);
CREATE INDEX "return_requests_order_id_idx" ON "return_requests" ("order_id");
CREATE INDEX "return_requests_user_id_idx" ON "return_requests" ("user_id");
CREATE TABLE "return_items" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "return_request_id" BIGINT NOT NULL, "order_item_id" BIGINT NOT NULL, "quantity" INTEGER NOT NULL, "reason" TEXT, FOREIGN KEY ("return_request_id") REFERENCES "return_requests" ("id") ON DELETE CASCADE, FOREIGN KEY ("order_item_id") REFERENCES "order_items" ("id") ON DELETE CASCADE, CHECK (quantity > 0));
CREATE INDEX "return_items_order_item_id_idx" ON "return_items" ("order_item_id");
CREATE UNIQUE INDEX "uq_return_order_item" ON "return_items" ("return_request_id", "order_item_id");
CREATE TABLE "refunds" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "order_id" BIGINT NOT NULL, "payment_id" BIGINT, "amount_cents" BIGINT NOT NULL, "currency" VARCHAR(3) NOT NULL, "reason" TEXT, "provider_reference" TEXT, "refunded_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY ("order_id") REFERENCES "orders" ("id") ON DELETE CASCADE, FOREIGN KEY ("payment_id") REFERENCES "payments" ("id") ON DELETE SET NULL, CHECK (amount_cents >= 0));
CREATE INDEX "refunds_order_id_idx" ON "refunds" ("order_id");
CREATE INDEX "refunds_payment_id_idx" ON "refunds" ("payment_id");
CREATE TABLE "reviews" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "user_id" BIGINT NOT NULL, "product_id" BIGINT NOT NULL, "order_item_id" BIGINT, "rating" INTEGER NOT NULL, "title" TEXT, "comment" TEXT, "is_verified_purchase" BOOLEAN NOT NULL, "is_published" BOOLEAN NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "deleted_at" TIMESTAMP, FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE, FOREIGN KEY ("product_id") REFERENCES "products" ("id") ON DELETE CASCADE, FOREIGN KEY ("order_item_id") REFERENCES "order_items" ("id") ON DELETE SET NULL, CHECK (rating >= 1 AND rating <= 5));
CREATE INDEX "reviews_product_id_idx" ON "reviews" ("product_id");
CREATE INDEX "reviews_order_item_id_idx" ON "reviews" ("order_item_id");
CREATE UNIQUE INDEX "uq_user_product_order_review" ON "reviews" ("user_id", "product_id", "order_item_id");
CREATE TABLE "audit_logs" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "actor_user_id" BIGINT, "entity_type" TEXT NOT NULL, "entity_id" BIGINT, "action" TEXT NOT NULL, "before_data" TEXT, "after_data" TEXT, "ip_address" TEXT, "user_agent" TEXT, "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY ("actor_user_id") REFERENCES "users" ("id") ON DELETE SET NULL);
CREATE INDEX "audit_logs_actor_user_id_idx" ON "audit_logs" ("actor_user_id");

-- migrate:down
DROP TABLE IF EXISTS "audit_logs";
DROP TABLE IF EXISTS "reviews";
DROP TABLE IF EXISTS "refunds";
DROP TABLE IF EXISTS "return_items";
DROP TABLE IF EXISTS "return_requests";
DROP TABLE IF EXISTS "shipment_items";
DROP TABLE IF EXISTS "shipments";
DROP TABLE IF EXISTS "payments";
DROP TABLE IF EXISTS "coupon_redemptions";
DROP TABLE IF EXISTS "order_addresses";
DROP TABLE IF EXISTS "order_items";
DROP TABLE IF EXISTS "orders";
DROP TABLE IF EXISTS "coupons";
DROP TABLE IF EXISTS "cart_items";
DROP TABLE IF EXISTS "carts";
DROP TABLE IF EXISTS "inventory_movements";
DROP TABLE IF EXISTS "inventory_items";
DROP TABLE IF EXISTS "inventory_locations";
DROP TABLE IF EXISTS "product_images";
DROP TABLE IF EXISTS "product_variants";
DROP TABLE IF EXISTS "product_categories";
DROP TABLE IF EXISTS "products";
DROP TABLE IF EXISTS "categories";
DROP TABLE IF EXISTS "brands";
DROP TABLE IF EXISTS "vendor_members";
DROP TABLE IF EXISTS "vendors";
DROP TABLE IF EXISTS "addresses";
DROP TABLE IF EXISTS "users";
